import { describe, expect, it } from "vitest";
import { renderHtml, renderText } from "./render.js";
import type { DigestIssue } from "./types.js";

const issue: DigestIssue = {
  title: "Latest updates",
  preheader: "Two posts from the blog.",
  intro: "A short digest.",
  sourceLabel: "Example",
  generatedAt: "2026-05-31T00:00:00.000Z",
  items: [
    {
      title: "First post",
      summary: "A useful summary.",
      url: "https://example.com/first",
      date: "2026-05-30",
    },
  ],
};

describe("renderers", () => {
  it("renders email html", () => {
    const html = renderHtml(issue);
    expect(html).toContain("<!doctype html>");
    expect(html).toContain("Latest updates");
    expect(html).toContain("https://example.com/first");
  });

  it("renders plain text", () => {
    const text = renderText(issue);
    expect(text).toContain("Latest updates");
    expect(text).toContain("1. First post");
    expect(text).toContain("https://example.com/first");
  });

  it("renders an unsubscribe link when set", () => {
    const withUnsub = { ...issue, unsubscribeUrl: "{{unsubscribe_url}}", footerNote: "Sent by Example." };
    const html = renderHtml(withUnsub);
    expect(html).toContain("Unsubscribe");
    expect(html).toContain("{{unsubscribe_url}}");
    expect(html).toContain("Sent by Example.");
    expect(html).not.toContain("Generated by Feedletter");

    const text = renderText(withUnsub);
    expect(text).toContain("Unsubscribe: {{unsubscribe_url}}");
    expect(text).toContain("Sent by Example.");
  });

  it("escapes html in item fields", () => {
    const xss = {
      ...issue,
      items: [{ title: "<script>alert(1)</script>", url: "https://example.com/x" }],
    };
    const html = renderHtml(xss);
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("shows a date-only value as the same day in every time zone", () => {
    const previous = process.env.TZ;
    try {
      for (const tz of ["America/Los_Angeles", "UTC", "Asia/Tokyo"]) {
        process.env.TZ = tz;
        const html = renderHtml({ ...issue, items: [{ title: "Dated", date: "2026-05-30" }, { title: "Yaml", date: "2026-05-30T00:00:00.000Z" }] });
        expect(html.match(/May 30, 2026/g)).toHaveLength(2);
      }
    } finally {
      if (previous === undefined) delete process.env.TZ;
      else process.env.TZ = previous;
    }
  });

  it("pads the preheader and only renders it when set", () => {
    expect(renderHtml(issue)).toContain("Two posts from the blog.&#847;&zwnj;&nbsp;");
    expect(renderHtml({ ...issue, preheader: "" })).not.toContain("mso-hide:all");
  });

  it("includes Outlook fallbacks and a mobile breakpoint", () => {
    const html = renderHtml(issue);
    expect(html).toContain('<!--[if mso]><table role="presentation" width="680"');
    expect(html).toContain('bgcolor="#059669"');
    expect(html).toContain("@media only screen and (max-width:480px)");
  });
});
