import type { DigestIssue, SourceItem } from "./types.js";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatDate(value?: string) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  // A date with no time (2026-05-30) is a calendar day, which JavaScript parses
  // as midnight UTC. Format it in UTC so it is not shown as the day before west
  // of UTC. Real timestamps, midnight included, are formatted as instants.
  const dateOnly = /^\d{4}-\d{2}-\d{2}$/.test(value.trim());
  return new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "numeric",
    ...(dateOnly ? { timeZone: "UTC" } : {}),
  }).format(date);
}

// Padding after the preheader so inbox previews do not run on into the body text.
const PREHEADER_PADDING = "&#847;&zwnj;&nbsp;".repeat(60);

function readingHost(item: SourceItem) {
  if (!item.url) return "";
  try {
    return new URL(item.url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

function renderItem(item: SourceItem) {
  const title = escapeHtml(item.title);
  const summary = item.summary ? escapeHtml(item.summary) : "";
  const date = formatDate(item.date);
  const host = readingHost(item);
  const meta = [date, item.author, host].filter(Boolean).join(" · ");
  const titleHtml = item.url
    ? `<a href="${escapeHtml(item.url)}" style="color:#111827;text-decoration:none;">${title}</a>`
    : title;
  const image = item.image && /^https?:\/\//i.test(item.image) ? escapeHtml(item.image) : "";
  const imageHtml = image
    ? `<img src="${image}" alt="" width="678" border="0" style="display:block;width:100%;max-width:100%;height:auto;border:0;outline:none;text-decoration:none;border-radius:16px 16px 0 0;" />`
    : "";
  const linkedImage = imageHtml && item.url ? `<a href="${escapeHtml(item.url)}" style="text-decoration:none;">${imageHtml}</a>` : imageHtml;

  return `
    <tr>
      <td style="padding:0 0 14px;">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="border:1px solid #e5e7eb;border-radius:16px;background:#ffffff;overflow:hidden;">
          ${linkedImage ? `<tr><td style="padding:0;">${linkedImage}</td></tr>` : ""}
          <tr>
            <td class="fl-card" style="padding:20px 20px 18px;">
              ${meta ? `<div style="margin-bottom:10px;font-size:12px;line-height:18px;color:#64748b;">${escapeHtml(meta)}</div>` : ""}
              <h2 style="margin:0 0 9px;font-size:20px;line-height:28px;color:#111827;font-weight:800;overflow-wrap:break-word;word-wrap:break-word;">${titleHtml}</h2>
              ${summary ? `<p style="margin:0 0 16px;font-size:15px;line-height:24px;color:#475569;">${summary}</p>` : ""}
              ${
                item.url
                  ? `<table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td bgcolor="#059669" style="border-radius:999px;background:#059669;mso-padding-alt:9px 14px;"><a href="${escapeHtml(item.url)}" style="display:inline-block;padding:9px 14px;font-size:13px;line-height:18px;color:#ffffff;font-weight:700;text-decoration:none;">Read the post</a></td></tr></table>`
                  : ""
              }
            </td>
          </tr>
        </table>
      </td>
    </tr>`;
}

export function renderHtml(issue: DigestIssue) {
  const title = escapeHtml(issue.title);
  const preheader = escapeHtml(issue.preheader);
  const intro = escapeHtml(issue.intro);

  const generated = escapeHtml(formatDate(issue.generatedAt));
  const itemCount = `${issue.items.length} item${issue.items.length === 1 ? "" : "s"}`;

  const footerBits: string[] = [];
  if (issue.footerNote) {
    footerBits.push(`<p style="margin:0 0 6px;font-size:12px;line-height:19px;color:#64748b;">${escapeHtml(issue.footerNote)}</p>`);
  }
  if (issue.unsubscribeUrl) {
    footerBits.push(
      `<p style="margin:0;font-size:12px;line-height:19px;color:#64748b;"><a href="${escapeHtml(issue.unsubscribeUrl)}" style="color:#059669;text-decoration:underline;">Unsubscribe</a></p>`,
    );
  } else {
    footerBits.push(
      `<p style="margin:0;font-size:12px;line-height:19px;color:#64748b;">Generated by Feedletter on ${generated}. You can edit this HTML before sending or use issue.json with your own template.</p>`,
    );
  }
  const footer = footerBits.join("");

  return `<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="x-apple-disable-message-reformatting">
    <meta name="format-detection" content="telephone=no,date=no,address=no,email=no">
    <title>${title}</title>
    <!--[if mso]><noscript><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]-->
    <style>
      @media only screen and (max-width:480px) {
        .fl-outer { padding:16px 8px !important; }
        .fl-hero { padding:26px 20px 22px !important; }
        .fl-h1 { font-size:27px !important; line-height:34px !important; }
        .fl-card { padding:18px 16px 16px !important; }
      }
    </style>
  </head>
  <body style="margin:0;padding:0;background:#eef2f7;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
    ${preheader ? `<div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${preheader}${PREHEADER_PADDING}</div>` : ""}
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#eef2f7" style="background:#eef2f7;">
      <tr>
        <td align="center" class="fl-outer" style="padding:28px 14px;">
          <!--[if mso]><table role="presentation" width="680" align="center" cellspacing="0" cellpadding="0" border="0"><tr><td><![endif]-->
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:680px;">
            <tr>
              <td style="padding:0 0 14px;">
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#0b0b0c" style="overflow:hidden;border-radius:22px;background:#0b0b0c;">
                  <tr>
                    <td height="16" bgcolor="#10b981" style="height:16px;padding:0;background:#10b981;font-size:0;line-height:0;">&nbsp;</td>
                  </tr>
                  <tr>
                    <td class="fl-hero" style="padding:34px 30px 30px;">
                      <div style="margin-bottom:18px;">
                        <span style="display:inline-block;border:1px solid rgba(255,255,255,.18);border-radius:999px;padding:7px 10px;font-size:12px;line-height:16px;color:#d1fae5;font-weight:700;">${escapeHtml(issue.sourceLabel)}</span>
                        <span style="display:inline-block;margin-left:8px;border:1px solid rgba(255,255,255,.14);border-radius:999px;padding:7px 10px;font-size:12px;line-height:16px;color:#cbd5e1;">${escapeHtml(itemCount)}</span>
                      </div>
                      <h1 class="fl-h1" style="margin:0 0 14px;font-size:34px;line-height:42px;color:#ffffff;font-weight:800;overflow-wrap:break-word;word-wrap:break-word;">${title}</h1>
                      <p style="margin:0;font-size:16px;line-height:26px;color:#cbd5e1;">${intro}</p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td style="padding:0;">
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
                  ${issue.items.map(renderItem).join("")}
                </table>
              </td>
            </tr>
            <tr>
              <td style="padding:4px 2px 0;">
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f8fafc" style="border-radius:16px;background:#f8fafc;border:1px solid #e2e8f0;">
                  <tr>
                    <td style="padding:18px 20px;">
                      ${footer}
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          <!--[if mso]></td></tr></table><![endif]-->
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

export function renderText(issue: DigestIssue) {
  const lines = [
    issue.title,
    "",
    issue.intro,
    "",
    ...issue.items.flatMap((item, index) => [
      `${index + 1}. ${item.title}`,
      item.summary ?? "",
      item.url ?? "",
      "",
    ]),
    ...(issue.footerNote ? [issue.footerNote] : []),
    issue.unsubscribeUrl
      ? `Unsubscribe: ${issue.unsubscribeUrl}`
      : `Generated by Feedletter on ${formatDate(issue.generatedAt)}.`,
    "",
  ];

  return lines.filter((line, index, all) => line || all[index - 1] !== "").join("\n");
}
